In [20]:
import json
import pandas as pd

In [21]:
def grid_dicto_to_df_list(grid_list):
    list_to_df = []
    non_metrics = ['proba_outputs', 'actual_classes', 'proba_outputs', 'actual_classes', 'test_proba', 'test_actual_classes']
    for dict_hyper in grid_list:
        dict_to_df = {}
        # print(dict_hyper)
        for val in dict_hyper.values():
            for item in val.items():
                if type(item[1]) != dict:
                    dict_to_df[item[0]] = item[1]
                else:
                    dictionary_results = item[1]
                    for item in dictionary_results.items(): 
                        if item[0] not in non_metrics:
                            dict_to_df[item[0]] = item[1]
        list_to_df.append(dict_to_df)
    return list_to_df

In [22]:
with open("metrics_ind_dets_final.json") as f:
    grids = json.load(f)

In [23]:
grids[0]["metrics"]["epoch_0"].keys()

dict_keys(['train_loss_epoch_1', 'valid_loss_epoch_1', 'f1_epoch_1', 'accuracy_epoch_1', 'roc_auc_epoch_1', 'hamming_epoch_1', 'proba_outputs_epoch_1', 'actual_classes_epoch_1'])

In [24]:
proba = grids[0]["metrics"]["epoch_39"]["proba_outputs_epoch_40"]

targets = grids[0]["metrics"]["epoch_39"]["actual_classes_epoch_40"]

In [25]:
import numpy as np

# Why hamming score is not ideal

In [26]:
list_indexes = []
targets_study = []
for target in targets:
    index_1 = targets.index(target)
    counts = target.count(1.0)
    # print(counts)
    if counts > 1:
        # print(target)
        # print(index_1)
        list_indexes.append(index_1)
        targets_study.append(target)

In [34]:
len(targets_study[0])

18

In [29]:
pro_study = []
for probs in proba:
    for prob in probs:
        index = probs.index(prob)
        if index in list_indexes:
            # print(prob)
            pro_study.append(prob)

In [35]:
len(pro_study[1])

18

In [30]:
df = pd.read_csv("nancy_determinants_individual_labels_eng.csv")
categories = list(df.columns[1:])

In [36]:
len(categories)

18

In [37]:
df_hammer = pd.DataFrame([targets_study[0], pro_study[0]], columns=categories)

In [43]:
df_hammer.index = ["Actual class", "Probability"]

In [47]:
print(df_hammer.T.to_latex())

\begin{tabular}{lrr}
\toprule
 & Actual class & Probability \\
\midrule
C & 1.000000 & 0.166108 \\
C' & 0.000000 & 0.005703 \\
C'F & 0.000000 & 0.002555 \\
CF & 0.000000 & 0.004314 \\
CF' & 0.000000 & 0.002793 \\
CLOB & 0.000000 & 0.009092 \\
CLOBF & 0.000000 & 0.002442 \\
E & 0.000000 & 0.012736 \\
EF & 0.000000 & 0.003250 \\
F & 0.000000 & 0.006959 \\
FC & 0.000000 & 0.005460 \\
FC' & 0.000000 & 0.004787 \\
FCLOB & 0.000000 & 0.004081 \\
FE & 0.000000 & 0.002069 \\
K & 1.000000 & 0.946964 \\
KAN & 0.000000 & 0.018132 \\
KOB & 0.000000 & 0.002614 \\
KP & 0.000000 & 0.009034 \\
\bottomrule
\end{tabular}



Same but for macros

In [62]:
with open("metrics_macro_dets_final.json") as f:
    grids = json.load(f)

In [63]:
proba = grids[0]["metrics"]["epoch_39"]["proba_outputs_epoch_40"]

targets = grids[0]["metrics"]["epoch_39"]["actual_classes_epoch_40"]

In [66]:
proba[0][0]

[0.9941744208335876,
 0.003322105621919036,
 0.0016201183898374438,
 0.001091857091523707,
 0.0010845869546756148,
 0.0016021255869418383,
 0.0010661340784281492,
 0.0015613246941938996,
 0.0018880752613767982,
 0.0013919611228629947,
 0.0022954228334128857]

In [54]:
list_indexes = []
targets_study = []
for target in targets:
    index_1 = targets.index(target)
    counts = target.count(1.0)
    # print(counts)
    if counts > 1:
        # print(target)
        # print(index_1)
        list_indexes.append(index_1)
        targets_study.append(target)
        
print(len(targets_study[0]))

11


In [55]:
pro_study = []
for probs in proba:
    for prob in probs:
        index = probs.index(prob)
        if index in list_indexes:
            # print(prob)
            pro_study.append(prob)

In [56]:
len(pro_study[0])

11

In [60]:
df = pd.read_csv("nancy_determinants_macro_labels_english.csv")
categories = list(df.columns[1:])

In [67]:
df

Answer (English)  color_sum  threat_sum  \
0     It reminds me of a moth with mandibles. It lo...          1           0   
1    One person on each side (obviously, it’s symme...          0           0   
2    A saucepan on a…camping gas stove. The gas sto...          0           0   
3    Ah two rabbits hitting each other's hands with...          0           0   
4    And... A person with big lips, his eyes, his e...          0           0   
..                                                 ...        ...         ...   
375  You see that, it reminds me\n reminds me of sh...          1           0   
376  I really can't\n see the whole thing, it makes...          1           0   
377  It's a bit capillotint\n a bit afterwards, but...          0           0   
378  : It reminds me of a goat\n goat (laughs), and...          1           0   
379  You've got a chasm, you see,\n you've got the ...          0           0   

     fading_sum  form_sum  kinesthetics_sum  
0             0         0                 0  
1             0         0                 1  
2             1         0                 0  
3             0         0                 1  
4             1         0                 0  
..          ...       ...               ...  
375           0         0                 0  
376           0         0                 0  
377           1         0                 1  
378           0         0                 0  
379           1         0                 1  

[380 rows x 6 columns]

In [61]:
len(categories)

5

# Scoring per label

In [32]:
# calculating predictions

threshold = 0.5
for prob in proba:
    for pro in prob:
        pro = np.array(pro)
        y_pred = np.zeros(pro.shape)
        y_pred[np.where(pro>=threshold)] = 1
        # print(pro)
        if 1 not in y_pred:
            idx = np.argmax(pro)
            y_pred[idx] = 1.0
        print(y_pred)
        print(len(y_pred))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
18
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
